name: ChildsGame
main: me.sabbertran.childsgame.ChildsGame
version: 1.0
website: http://www.sabbertran.tk/
author: Sabbertran
description: ChildsGame Plugin
depend: [ProtocolLib, LibsDisguises]
commands:
  hideandseek:
    description: HideAndSeek Command
    usage: "/hideandseek"
    aliases: [has]
  arena:
    description: HideAndSeek Arena Command
    usage: "/arena"
  leave:
    description: HideAndSeek Leave Command
    usage: "/leave"
permissions:
   childsgame.user.arena.join:
     description: Allows the player to join an arena
     default: false
   childsgame.user.arena.leave:
     description: Allows the player to use the /leave command
     default: false
   childsgame.admin.arena.create:
     description: Allows the player to use the /arena create command to create an arena
     default: false
   childsgame.admin.arena.tool:
     description: Allows the player to use the /arena tool command and to use the tool
     default: false
   childsgame.admin.arena.blocks:
     description: Allows the player to use the /arena blocks command to setup blocks for an arena
     default: false
   childsgame.admin.arena.sign:
     description: Allows the player to create an arena sign
     default: op
   childsgame.admin.arena.list:
     description: Allows the player to use the /arena list command to get a list of all existing arenas
     default: op
   childsgame.admin.arena.delete:
     description: Allows the player to use the /arena delete command to delete an arena
     default: op
   childsgame.*:
     description: Gives access to all permissions
     default: false
     children:
       childsgame.admin.*: true
       childsgame.user.*: true
   childsgame.admin.*:
     description: Gives access to all admin permissions
     default: false
     children:
       childsgame.admin.arena.create: true
       childsgame.admin.arena.tool: true
       childsgame.admin.arena.blocks: true
       childsgame.admin.arena.sign: true
       childsgame.admin.arena.list: true
   childsgame.user.*:
     description: Gives access to all user permissions
     default: false
     children:
       childsgame.user.arena.join: true
       childsgame.user.arena.leave: true
    